baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Thang Van's blog"
theme: "./.."
relativeURLs: true

googleanalytics: 
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/fav-microservices.png"
  description: "Some stuffs I would like to share..."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/avatar.jpeg"
  name: "Truong Quoc Thang Van"
  namecolor: ffc107
  profession: "Software Developer"
  github: "https://github.com/justinvan0603"
  linkedin: "https://www.linkedin.com/in/thang-van/"
  instagram: "https://www.instagram.com/thangvtq/"
  facebook: "https://www.facebook.com/thangvan.cs"

  # Custom social links
  customSocialLinks:
    - fontAwesomeIconName: "fab fa-xing"
      url: "https://www.xing.com/profile/TruongQuocThang_Van/"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Thang. I'm a Software Developer. My job is about Backend development with JakartaEE and Microservices Architecture. Besides sticking to the notebook, I also love taking landscape photos. Thanks for visiting my little page, where I share some of my stuffs."
  descripe_l2_person: "You can find my works [here](#projects)"
  skills:
    - name: Java
      disable_percentage: true
      percentage: 100
    - name: JakartaEE
      percentage: 100
    - name: Docker
      percentage: 100
    - name: BPMN/ DMN
      percentage: 100
    - name: Microservices Architecture
      percentage: 100
    - name: RESTful Webservices
      percentage: 100

  # Experience
  disable_experience: false
  experience:
    - company: "tech11 GmbH"
      id: "dev"
      role: "Software developer"
      startdate: Nov 2020
      enddate: present
      featuredpoints:
        - point: Backend software developer.
        - point: Developing insurance platform and customizing features for clients in projects.
    - company: "tech11 GmbH"
      id: "junior-dev"
      role: "Junior software developer"
      startdate: Oct 2019
      enddate: Oct 2020
      featuredpoints:
        - point: Developing insurance platform.
    - company: "GSOFT Co Ltd."
      id: "gsoft-dev"
      role: "Software developer"
      startdate: Feb 2017
      enddate: Dec 2017
      featuredpoints:
        - point: Working as .Net developer.
        
  # Education
  disable_education: false
  education:
    - degree: "Master of Science"
      branch: "International Software Systems Science"
      university: "Otto-Friedrich-Universität Bamberg"
      startedyear: "2018"
      graduation: "2020"
    - degree: "Bachelor of Engineering"
      branch: "Software Technology"
      university: "University of information technology - VNUHCM"
      startedyear: "2013"
      graduation: "2018"

  # Projects
  disable_projects: false
  projects:
    - name: "Nexsurance"
      img: ./images/project.jpg
      description: "Customize insurance platform, business processes, and integrate with B2C Channel."

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "thangvtq@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: true
  tweet: false
